/**
 * Where each body carries the rest of the monster, in sheet units.
 *
 * A body is not a shape the game invents a face for: it is one of Clara's six drawings, and
 * these numbers are the measured boxes of that drawing's own eyes, mouth, arms and legs,
 * put on the sheet. A piece worn by the creature it was cut from therefore lands back
 * exactly where the artist drew it, and a piece borrowed from another creature is fitted to
 * the same width so it sits on the face rather than beside it.
 *
 * GENERATED by art-source/approved/gen.cjs together with parts.tsx. The two are one contract: the
 * boxes here are the boxes there, measured from the same drawing.
 */

/** A place on the 600 x 720 sheet, by its middle and its size. */
export interface SlotRect {
  cx: number;
  cy: number;
  w: number;
  h: number;
  /** As wide as this row may be drawn, whatever the fitting says. Only the arms carry one. */
  max?: number;
}

export interface BodyLayout {
  /** The approved drawing this body, and these places, were cut from. */
  source: string;
  /** That creature's own colour. Every piece it wears is repainted from this. */
  main: string;
  body: SlotRect;
  eyes: SlotRect;
  mouth: SlotRect;
  arms: SlotRect;
  legs: SlotRect;
}

export const MONSTER_SHEET = { vw: 600, vh: 720 };

export const MONSTER_BODY_LAYOUT: Record<string, BodyLayout> = {
  // Fuzzbop
  round: {
    source: 'Fuzzbop',
    main: '#FF8A47',
    body: { cx: 311.96, cy: 340.27, w: 478.87, h: 497.48 },
    eyes: { cx: 311.96, cy: 240.77, w: 309.2, h: 195.42 },
    mouth: { cx: 313.56, cy: 435.92, w: 226.07, h: 112.66 },
    arms: { cx: 311.96, cy: 399.1, w: 582, h: 445.34 },
    legs: { cx: 311.96, cy: 574.55, w: 368.73, h: 161.99 },
  },
  // Wobble
  egg: {
    source: 'Wobble',
    main: '#5CDFC3',
    body: { cx: 302.55, cy: 324.11, w: 495.44, h: 624.23 },
    eyes: { cx: 302.55, cy: 199.26, w: 275.91, h: 198.86 },
    mouth: { cx: 302.48, cy: 335.45, w: 178.97, h: 93.84 },
    arms: { cx: 302.55, cy: 498.69, w: 535.69, h: 172.98 },
    legs: { cx: 302.55, cy: 640.89, w: 381.49, h: 187.28 },
  },
  // Bricky
  square: {
    source: 'Bricky',
    main: '#9B5DE5',
    body: { cx: 287.31, cy: 321.01, w: 395.07, h: 609.42 },
    eyes: { cx: 287.31, cy: 199.13, w: 269.18, h: 160.37 },
    mouth: { cx: 287.32, cy: 360.94, w: 263.91, h: 157.23 },
    arms: { cx: 287.31, cy: 461.27, w: 510.48, h: 306.94 },
    legs: { cx: 287.31, cy: 656.53, w: 304.2, h: 80.62 },
  },
  // Bumblepop
  hourglass: {
    source: 'Bumblepop',
    main: '#FFD24A',
    body: { cx: 296.8, cy: 347.57, w: 332.48, h: 671.15 },
    eyes: { cx: 296.8, cy: 213.34, w: 284.47, h: 186.03 },
    mouth: { cx: 298.99, cy: 318.95, w: 193.37, h: 58.76 },
    arms: { cx: 296.8, cy: 399.06, w: 345.96, h: 121.77 },
    legs: { cx: 296.8, cy: 674.02, w: 256.01, h: 46.05 },
  },
};
