/**
 * Every piece of the modelled monster, measured.
 *
 * GENERATED by art-source/approved/read-model.cjs from public/models/monstrinho.glb. His
 * pieces can be worn by any body, and to place one the game needs its size and its middle in
 * the model's own metres. Run that script again if the model is replaced.
 */
export interface ModelRow {
  /** The named groups of the GLB this row switches on. */
  groups: string[];
  /** The box it fills, in the model's own metres — Y up, feet at nought, facing +Z. */
  min: [number, number, number];
  max: [number, number, number];
  /** Arms only: the hole between the two of them, and where its middle sits across. */
  gap?: number;
  mid?: number;
}

export const MONSTRINHO_ROWS: Record<string, ModelRow> = {
  body: {
    groups: [
      'Corpo',
      'Juba',
      'Rosto',
      'Bochechas',
      'Pintinhas',
      'Chifres',
      'Topete'
    ],
    min: [
      -0.43,
      0.122,
      -0.308
    ],
    max: [
      0.421,
      1.2,
      0.274
    ]
  },
  eyes: {
    groups: [
      'Olhos',
      'Sobrancelhas'
    ],
    min: [
      -0.288,
      0.666,
      0.066
    ],
    max: [
      0.276,
      0.979,
      0.293
    ]
  },
  mouth: {
    groups: [
      'Boca'
    ],
    min: [
      -0.219,
      0.373,
      0.232
    ],
    max: [
      0.21,
      0.593,
      0.308
    ]
  },
  arms: {
    groups: [
      'Braco_E',
      'Braco_D'
    ],
    min: [
      -0.599,
      0.159,
      -0.192
    ],
    max: [
      0.599,
      1.049,
      0.054
    ],
    gap: 0.471,
    mid: -0.006
  },
  legs: {
    groups: [
      'Pernas'
    ],
    min: [
      -0.24,
      0,
      -0.159
    ],
    max: [
      0.228,
      0.28,
      0.08
    ]
  }
};
